### ISSUE TITLE
Messages in the console when running AquaCrop

### ISSUE THREAD

**Issue by destrella28** [tdeswaef/aquacroponr#2]
Rows: 70 Columns: 47
── Column specification ───────────────────────────────────────────────────────────────────

dbl (47): X1, X2, X3, X4, X5, X6, X7, X8, X9, X10, X11, X12, X13, X14, X15, X16, X17, X...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 70 Columns: 47

**Comment by destrella28** [comment]
Silence these messages and maybe show another message like "Runing AquaCrop...."

**Comment by tdeswaef** [comment]
Solved!
